"""_index.py -- regenerate tools/README.md, the catalogue of what already exists.

    python pyctrl/tools/_index.py            # rewrite README.md
    python pyctrl/tools/_index.py --audit    # also list cleaning candidates, write nothing

This exists because the expensive failure mode in this repo is not a missing tool, it is an agent
re-deriving an analysis that already exists -- one session wrote thirteen throwaway scripts in five
minutes, six of which duplicated `imaging_round.py` and the analysis package. A catalogue only helps
if it cannot rot, so it is generated from the modules' own docstrings rather than maintained by hand.

Each entry is the file, its one-line summary (first docstring line), and whether a skill names it.
A tool with no docstring cannot be found by anyone and is flagged.
"""
import ast
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SKILLS = os.path.join(REPO, "yb_skills", "skills")


def _summary(path):
    try:
        src = open(path, encoding="utf-8", errors="replace").read()
        doc = ast.get_docstring(ast.parse(src))
    except Exception:
        return None, 0
    n = len(src.splitlines())
    if not doc:
        return None, n
    first = doc.strip().splitlines()[0]
    # our docstrings start "name.py -- what it does"; keep the prose half
    if "--" in first:
        first = first.split("--", 1)[1].strip()
    return first.strip(), n


def _referenced():
    """Set of tool basenames named anywhere in the skills."""
    hits = set()
    if not os.path.isdir(SKILLS):
        return hits
    try:
        out = subprocess.run(["grep", "-rho", r"[A-Za-z0-9_]*\.py", SKILLS],
                             capture_output=True, text=True).stdout
        hits = {l.strip() for l in out.splitlines() if l.strip()}
    except Exception:
        pass
    return hits


def collect():
    ref = _referenced()
    rows = []
    for f in sorted(os.listdir(HERE)):
        if not f.endswith(".py"):
            continue
        p = os.path.join(HERE, f)
        doc, n = _summary(p)
        rows.append({"file": f, "doc": doc, "loc": n, "referenced": f in ref,
                     "mtime": os.path.getmtime(p)})
    return rows


def write_readme(rows):
    out = os.path.join(HERE, "README.md")
    L = []
    L.append("# `pyctrl/tools/` — what already exists")
    L.append("")
    L.append("**Read this before writing an analysis script.** Generated by `python pyctrl/tools/_index.py`")
    L.append("from each module's own docstring — do not hand-edit; fix the docstring instead.")
    L.append("")
    L.append("If a tool here covers your question, run it. If one nearly covers it, extend it. Write a new")
    L.append("script only when neither is true, and then it belongs here with a docstring, not in `tmp/`.")
    L.append("")
    L.append("| tool | what it does | loc | named by a skill |")
    L.append("|---|---|---|---|")
    for r in sorted(rows, key=lambda r: r["file"]):
        doc = r["doc"] or "**(no docstring — undiscoverable, needs one or needs deleting)**"
        L.append("| `%s` | %s | %d | %s |"
                 % (r["file"], doc, r["loc"], "yes" if r["referenced"] else ""))
    L.append("")
    L.append("_%d tools, %d documented, %d named by a skill. Regenerated %s._"
             % (len(rows), sum(1 for r in rows if r["doc"]),
                sum(1 for r in rows if r["referenced"]),
                time.strftime("%Y-%m-%d")))
    open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("wrote", out, "(%d tools)" % len(rows))


def audit(rows):
    old = time.time() - 90 * 86400
    undoc = [r for r in rows if not r["doc"]]
    orphan = [r for r in rows if r["doc"] and not r["referenced"] and r["mtime"] < old]
    print("CLEANING CANDIDATES")
    print("\n  NO DOCSTRING (%d) -- cannot be found by anyone; document or delete:" % len(undoc))
    for r in undoc:
        print("    %-36s %4d loc" % (r["file"], r["loc"]))
    print("\n  UNDOCUMENTED BY ANY SKILL AND UNTOUCHED >90 DAYS (%d) -- likely one-offs:" % len(orphan))
    for r in sorted(orphan, key=lambda r: r["mtime"]):
        print("    %-36s %4d loc   last touched %s"
              % (r["file"], r["loc"], time.strftime("%Y-%m-%d", time.localtime(r["mtime"]))))


if __name__ == "__main__":
    rows = collect()
    if "--audit" in sys.argv:
        audit(rows)
    else:
        write_readme(rows)
